### ISSUE TITLE
Unable to query anything

### ISSUE THREAD

**Issue by igorline** [ledgerwatch/turbo-geth#1273]
When I try to query block number using `curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id":1}' localhost:9045` I'm getting 
`{"jsonrpc":"2.0","id":1,"result":"0x0"}`.

I'm running tg using datadir flag `./build/bin/tg --datadir /turbo/data`, node is synced and processing new blocks and rpcdaemon with different http.port `./build/bin/rpcdaemon --chaindata /turbo/data/tg --http.api=eth,debug,net,web3 --http.port 9045`

I'm on a master branch commit `716a0f2dbaa5e355c7967b024377922463cdb75f`

**Comment by AlexeyAkhunov** [comment]
Ok, currently communication via shared memory might not work for all RPC methods. So, I suggest you try two things:
1) Change `--chaindata /turbo/data/tg` to `--chaindata /turbo/data/tg/chaindata` This might work, but we do not recommend it yet if TG is running on the same database. Currently running rpc daemon with `--chaindata` should be used when TG is now accessing the same database
2) Use `--private.api.addr localhost:9090` for both TG and RPC daemon, and remove `--chaindata` parameter from RPC daemon, they will connect via TPC, this should definitely work

**Comment by tjayrush** [comment]
@AlexeyAkhunov I think this is what you and I talked about yesterday. I'll try to look into this.

I started TG with `--datadir=WHATEVER`, and then started the RPC daemon with `--chaindata=WHATEVER/tg/chaindata`. I then wrote a short script that uses `curl` to repeatedly call `eth_blockNumber` (once every second) expecting that the results wouldn't change (I thought that's how it would work).

I found that the `blockNumber` was updating each time `TG` processed a new block.

@igorline Am I understanding what you were trying to do?  Does adding `chaindata` to the RPC daemon path fix the issue?

Perhaps the bug is that the RPC daemon should report if it can't find the database in the provided `--chaindata` path.

**Comment by AskAlexSharov** [comment]
@tjayrush also there is a problem that `rawdb.ReadBlockByNumber` doesn't return error. 
I created issue to start changing it: https://github.com/ledgerwatch/turbo-geth/issues/1261
take it also if you can plz.

**Comment by AskAlexSharov** [comment]
@tjayrush , code which creates non-existing folder in method `kv_lmdb:Open` -> `os.MkdirAll`

i thinking about next change: 
- RPCDaemon to open lmdb in ReadOnly mode. Code is in `cmd/rpcdaemon/cli:OpenDB`
- change `kv_lmdb:Open` method - if db opened in ReadOnly mode it doesn't create folder and if it doesn't exists return error instead.

**Comment by igorline** [comment]
Sorry for disappearing :)

@AlexeyAkhunov, `--private.api.addr localhost:9090` worked as expected

@tjayrush I was just trying to read data from the node without success following installation instructions in the documentation without success.

So using `chaindata` flag is not recommended atm?

**Comment by AskAlexSharov** [comment]
we fixed `chaindata` flag last week.

**Comment by AskAlexSharov** [comment]
@igorline we fixed `chaindata` flag last week, feel free to try it. Thank.

**Comment by igorline** [comment]
@AskAlexSharov it works! Would be great to have default `chaindata` locations specified not only for Mac OS here https://github.com/ledgerwatch/turbo-geth#json-rpc-daemon

Do you have any public communication channel? I still have some questions but don't know where to ask :)

**Comment by AskAlexSharov** [comment]
@igorline 
we supporting XDG_DATA_HOME ( https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html ) 
yep, you are welcome here: https://discord.gg/MGyuSztJ
